- name: mongodb server configuration
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb server
    ansible.builtin.dnf:
      name: mongodb-org
      state: present