- name: redis server configuration
  hosts: redis
  become: yes
  tasks:
  - name: disable redis
    ansible.builtin.command: dnf module disable redis -y

  - name: enable redis
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: install redis
    ansible.builtin.dnf:
      name: redis
      state: present
  
  - name: Update listen port address
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  
  - name: disable protected mode
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: protected-mode no
  
  - name: enable and start redis
    ansible.builtin.serivce:
      name: redis
      state: started
      enable: yes